### ISSUE TITLE
Allow t_funcs to be set without field number

### ISSUE THREAD

**Issue by tommyogden** [tommyogden/maxwellbloch#38]
I want the fields to be defined without the field number, i.e. `rabi_freq_t_func: gaussian` instead of `rabi_freq_t_func: gaussian_1`.

I could do this in `OBAtom.build_fields`. Take each dict and append the number there.

**Comment by tommyogden** [comment]
The problem the `gaussian_1`, `gaussian_2` setup works around is that all the time-dependent args need to be passed in the same dict, and so need to be differentiated (e.g. with two pulses, we can't have that dict including {'width': 1, 'width': 2}).

**Comment by amcdawes** [comment]
I'm finally diving back in to this, and I'm not sure I see where the issue is. I do see that the fields get built into a list and a dict within that, but they seem to remain independent enough to be re-used if needed. As an example, I can take the json portion of the example mb-solve-vee-sech-1.41pi-1.41pi notebook and simply change the second field term to sech_1 also, and it works the same as if it were sech_2. I even compare running different values in the two sech_1 fields (i.e. amp of 1.0 in one and amp of 0.5 in the other). To be clear, the following json still works when all sech functions are sech_1 (i.e. the following gives the same results as if I were to change the [0,2] coupling field to use sech_2).

`mb_solve_json = """
{
  "ob_atom": {
    "decays": [
      { "channels": [[0,1], [0,2]], 
        "rate": 0.0
      }
    ],
    "energies": [],
    "fields": [
      {
        "coupled_levels": [[0, 1]],
        "detuning": 0.0,
        "detuning_positive": true,
        "label": "probe",
        "rabi_freq": 0.592839341136,
        "rabi_freq_t_args": 
          {
             "ampl_1": 1.0,
             "centre_1": 0.0,
             "width_1": 0.3796628587572578
          },
        "rabi_freq_t_func": "sech_1"
      },
      {
        "coupled_levels": [[0, 2]],
        "detuning": 0.0,
        "detuning_positive": true,
        "label": "coupling",
        "rabi_freq": 0.592839341136,
        "rabi_freq_t_args": 
          {
             "ampl_1": 0.5,
             "centre_1": 0.0,
             "width_1": 0.3796628587572578
          },
        "rabi_freq_t_func": "sech_1"
      }
    ],
    "num_states": 3
  },
  "t_min": -2.0,
  "t_max": 10.0,
  "t_steps": 120,
  "z_min": -0.2,
  "z_max": 1.2,
  "z_steps": 140,
  "z_steps_inner": 1,
  "num_density_z_func": "square_1",
  "num_density_z_args": {
    "on_1": 0.0,
    "off_1": 1.0,
    "ampl_1": 1.0
  },
  "interaction_strengths": [10.0, 10.0],
  "velocity_classes": {
    "thermal_delta_min": -0.0,
    "thermal_delta_max": 0.0,
    "thermal_delta_steps": 0,
    "thermal_delta_inner_min": 0.0,
    "thermal_delta_inner_max": 0.0,
    "thermal_delta_inner_steps": 0,
    "thermal_width": 1.0
  },
  "method": "mesolve",
  "opts": {},
  "savefile": "qu/%s"
}
"""%(NOTEBOOK_NAME)`

**Comment by amcdawes** [comment]
Looking more closely, each field is still its own `Field` object in the list of fields:
```
[Field(label=probe, coupled_levels=[[0, 1]], detuning=0.0, detuning_positive=True, rabi_freq=0.592839341136, rabi_freq_t_func=<function sech_1 at 0x10f48ed90>, rabi_freq_t_args={'ampl_1': 1.0, 'centre_1': 0.0, 'width_1': 0.3796628587572578}),
 Field(label=coupling, coupled_levels=[[0, 2]], detuning=0.0, detuning_positive=True, rabi_freq=0.592839341136, rabi_freq_t_func=<function sech_1 at 0x10f48ed90>, rabi_freq_t_args={'ampl_1': 0.5, 'centre_1': 0.0, 'width_1': 0.3796628587572578})]
```

**Comment by tommyogden** [comment]
Thanks for looking at this, and thanks for the example.

You are correct that each `Field` is separate, the problem is that these are all merged into one dict here in [`OBAtom.get_field_args()`](
https://github.com/tommyogden/maxwellbloch/blob/master/maxwellbloch/ob_atom.py#L175-L180) before they are passed to the Qutip solver here in [`OBAtom.mesolve()`](https://github.com/tommyogden/maxwellbloch/blob/master/maxwellbloch/ob_atom.py#L205-L212). 

The Qutip solver can only take one `args` dict I believe. So I don't think the solver would be able to tell the two args apart unless they had different keys in the dict.

So it is interesting that your example works! Are the two `ampl_1` values input actually different in the output? I believe the behaviour of a dict update() is to overwrite existing key-value pairs, in which case both pulses would have an ampl of 0.5. I will run the example myself later to check.

**Comment by amcdawes** [comment]
I see, yes that makes sense and I understand the issue more thoroughly now. I was missing the point at which the `args` get passed to `mesolve`. The example "works" because it's hard to tell the difference between probing with amplitude 1.0 and amplitude 0.5. It's not equivalent physically, and knowing where the `args` go I understand why it works (even though it's wrong). I still think there is a way around this and I'll kick around some more ideas.

**Comment by tommyogden** [comment]
Hi @amcdawes, I think your original idea of using a closure (nested function) is the way to go. We would replace e.g. `square_1`, `square_2` in the t_funcs module with something like:

```py
def bind_square(idx):

    def square(t, args):       
        on = args['on'+str(idx)]
        off = args['off'+str(idx)]
        ampl = args['ampl'+str(idx)]

        return ampl*(t >= on)*(t <= off)

    square.__name__ = 'square' + str(idx) # Not really needed?
    return square 
```

so that 

```py
square1 = bind_square(1)
```

generates us an indexed function
```py
square1(t=2.0, args={'ampl1':3.0, 'on1':1.0, 'off1':4.0})
Out: 3.0
```

The args are fairly straightfoward, in that we just need to change the dict keys to include an index. So If we have...

```py
field_0_func = 'square'
field_0_args = {'on':0.0, 'off':1.0, 'ampl':2.0}

field_1_func = 'square'
field_1_args = {'on':0.0, 'off':1.0, 'ampl':2.0}
```

we could put these into a list

```py
field_args_list = [field_0_args, field_1_args]
```

and then use the field list index to produce a single list of indexed args:

```py
args_dict = {}
for i, args_i in enumerate(field_args_list):
    for key, value in args_i.items():
        args_dict[key+str(i)] = value      
print(args_dict)
Out: {'ampl1': 2.0, 'on0': 0.0, 'ampl0': 2.0, 'off1': 1.0, 'off0': 1.0, 'on1': 0.0}
```

What do you think?

**Comment by tommyogden** [comment]
The call to generate the `rabi_freq_t_func` would be made in [Field.build_rabi_freq_t_func](https://github.com/tommyogden/maxwellbloch/blob/master/maxwellbloch/field.py#L55-L62), which would need an additional argument of `field_idx` (default `=0`?).

**Comment by amcdawes** [comment]
Yes, this seems like the way to go. Given the complexity and importance of getting the `idx` to match etc. it may be best to have a function or two that just processes all the fields and does the binding and `arg` construction. As long as users don't have to muck around with the `args` directly, the order would be correct since it can be handled automatically. It also makes it easier to avoid sneaky bugs where you could accidentally use `ampl1` twice for example.
